# Generated by Django 5.2.7 on 2025-10-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
